import { Staff, Site } from './types';

export const INITIAL_SITES: Site[] = [
  {
    id: 'site-1',
    name: '渋谷スクエア 新築内装現場',
    address: '東京都渋谷区渋谷2-24-12',
    lat: 35.6580,
    lng: 139.7016,
    client_name: '東急建設様',
    work_description: '内装ボード貼り・配管設備点検',
    status: 'in_progress',
  },
  {
    id: 'site-2',
    name: '新宿駅南口 ビル改修現場',
    address: '東京都新宿区新宿4-1-6',
    lat: 35.6885,
    lng: 139.7005,
    client_name: '三井住友建設様',
    work_description: '高圧電気ケーブル敷設・分電盤交換',
    status: 'in_progress',
  },
  {
    id: 'site-3',
    name: '品川オフィス棟 原状回復現場',
    address: '東京都港区港南2-16-1',
    lat: 35.6284,
    lng: 139.7387,
    client_name: '野村不動産様',
    work_description: '天井照明LED化工事および撤去作業',
    status: 'in_progress',
  },
];

export const INITIAL_STAFFS: Staff[] = [
  {
    id: 'staff-1',
    name: '佐藤 健一 (社長)',
    role: '統括・現場監督',
    phone: '090-1111-2222',
    avatar_color: '#EF4444',
    status: 'available',
    current_site_name: '待機中（本社事務所）',
    lat: 35.6895,
    lng: 139.6917,
    status_note: '急な案件があればすぐ現場駆けつけ可能です',
    updated_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: 'staff-2',
    name: '田中 裕介',
    role: '主任電気工事士',
    phone: '090-2222-3333',
    avatar_color: '#3B82F6',
    status: 'working',
    current_site_name: '新宿駅南口 ビル改修現場',
    lat: 35.6885,
    lng: 139.7005,
    status_note: '分電盤結線作業中。15:00頃完了予定',
    updated_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: 'staff-3',
    name: '高橋 大地',
    role: '内装・ボード工',
    phone: '090-3333-4444',
    avatar_color: '#10B981',
    status: 'working',
    current_site_name: '渋谷スクエア 新築内装現場',
    lat: 35.6580,
    lng: 139.7016,
    status_note: 'ボード下地張り工程。順調です',
    updated_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
  },
  {
    id: 'staff-4',
    name: '渡辺 慎吾',
    role: '配管設備士',
    phone: '090-4444-5555',
    avatar_color: '#F59E0B',
    status: 'moving',
    current_site_name: '品川オフィス棟へ移動中',
    lat: 35.6450,
    lng: 139.7250,
    status_note: '首都高利用中。あと15分で品川現場に到着',
    updated_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'staff-5',
    name: '伊藤 翼',
    role: '見習い・施工補佐',
    phone: '090-5555-6666',
    avatar_color: '#8B5CF6',
    status: 'available',
    current_site_name: '渋谷スクエア周辺（待機）',
    lat: 35.6600,
    lng: 139.7050,
    status_note: '渋谷現場の資材搬入完了。次レスキュー急行可能',
    updated_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
];
