import { Staff, Site } from './types';

export const INITIAL_SITES: Site[] = [
  {
    id: 'site-1',
    name: '松山市駅前 再開発ビル内装現場',
    address: '愛媛県松山市湊町5-1-1',
    lat: 33.8358,
    lng: 132.7621,
    client_name: '大林組 四国支店様',
    work_description: '軽量鉄骨下地・耐火ボード貼り・空調配線',
    status: 'in_progress',
    startDate: '2026-09-01',
    endDate: '2026-11-30',
    notes: '市駅地下街からの資材搬入。朝8:00朝礼、ヘルメット顎紐・親綱使用を徹底。指定詰所は3Fです。',
  },
  {
    id: 'site-2',
    name: '今治新都市 商業施設設備改修現場',
    address: '愛媛県今治市にぎわい広場1-1',
    lat: 34.0535,
    lng: 132.9642,
    client_name: '五洋建設様',
    work_description: '受変電設備更新・LED幹線配管工事',
    status: 'in_progress',
    startDate: '2026-08-20',
    endDate: '2026-10-15',
    notes: '営業中テナントあり。粉塵対策養生徹底。停電・騒音作業は夜間21:00以降のみ実施可。',
  },
  {
    id: 'site-3',
    name: '新居浜臨海プラント 原状回復現場',
    address: '愛媛県新居浜市磯浦町17-5',
    lat: 33.9748,
    lng: 133.2755,
    client_name: '住友重機械工業様',
    work_description: 'プラント配管溶接・高圧分電盤点検',
    status: 'in_progress',
    startDate: '2026-09-10',
    endDate: '2026-10-31',
    notes: '入門時に構内安全パスおよび資格証の提示必須。防塵マスクおよび耐油安全靴着用厳守。',
  },
];

export const INITIAL_STAFFS: Staff[] = [
  {
    id: 'staff-1',
    name: '佐藤 健一 (社長)',
    role: '代表取締役・統括監理',
    phone: '089-911-2222',
    email: 'sato@craftsync-ehime.jp',
    isAdmin: true,
    avatar_color: '#EF4444',
    status: 'available',
    current_site_name: '待機中（松山本社事務所）',
    lat: 33.8416,
    lng: 132.7661,
    status_note: '愛媛県内全域の急な応援・現場確認いつでも急行可能です',
    updated_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: 'staff-2',
    name: '田中 裕介',
    role: '主任電気工事士',
    phone: '090-2222-3333',
    email: 'tanaka@craftsync-ehime.jp',
    isAdmin: false,
    avatar_color: '#3B82F6',
    status: 'working',
    current_site_name: '松山市駅前 再開発ビル内装現場',
    lat: 33.8358,
    lng: 132.7621,
    status_note: '分電盤結線作業中。15:00頃完了予定。松山市内なら急行可能',
    updated_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: 'staff-3',
    name: '高橋 大地',
    role: '内装・ボード工長',
    phone: '090-3333-4444',
    email: 'takahashi@craftsync-ehime.jp',
    isAdmin: false,
    avatar_color: '#10B981',
    status: 'working',
    current_site_name: '今治新都市 商業施設設備改修現場',
    lat: 34.0535,
    lng: 132.9642,
    status_note: '3Fボード下地張り工程順調。外部養生ブルーシート点検済',
    updated_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
  },
  {
    id: 'staff-4',
    name: '渡辺 慎吾',
    role: '配管設備士',
    phone: '090-4444-5555',
    email: 'watanabe@craftsync-ehime.jp',
    isAdmin: false,
    avatar_color: '#F59E0B',
    status: 'moving',
    current_site_name: '松山自動車道移動中（川内IC通過）',
    lat: 33.7915,
    lng: 132.9050,
    status_note: '松山道順調。あと30分ほどで新居浜現場に現着予定です',
    updated_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'staff-5',
    name: '伊藤 翼',
    role: '見習い・施工補佐',
    phone: '090-5555-6666',
    email: 'ito@craftsync-ehime.jp',
    isAdmin: false,
    avatar_color: '#8B5CF6',
    status: 'available',
    current_site_name: '松山市駅前周辺（資材受取・待機）',
    lat: 33.8370,
    lng: 132.7635,
    status_note: '市駅現場の追加資材受取完了。松山・伊予エリア出動可能です',
    updated_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
];
